### ISSUE TITLE
Add demo application

### ISSUE THREAD

**Issue by bambamboole** [rappasoft/laravel-5-boilerplate#1006]
It would be nice for new users when there is a demo application where they could see all features.

Any thoughts on this?

**Comment by Shuyinsama** [comment]
I can understand why this would be nice. But since this boilerplate is such a broad one I don't see it helping the project in the long run. People might think it is the only use of the boilerplate.

It's easy just to clone the repo and follow the install guide. It takes like 10 mins to set up a local install.

**Comment by bambamboole** [comment]
@Shuyinsama ok, I'm with you :-)
