### ISSUE TITLE
API Unauthorized

### ISSUE THREAD

**Issue by LunarDevelopment** [rappasoft/laravel-5-boilerplate#1019]
I'm running a fresh install of Boilerplate, but when I use vue axios to connect to an API route which has middleware auth:api I just get "Unauthenticated" back. 

I'm logged in as the seeded user@user.com and I've simply placed a new vue component into the dashboard view which makes an axios call when mounted(). 

These all look fine to me and it works without the middleware (but I need to see which user is making the request which is null without auth middleware), what am I missing ? 

bootstap.js
```javascript

let token = document.head.querySelector('meta[name="csrf-token"]');

if (token) {
    window.axios.defaults.headers.common['X-CSRF-TOKEN'] = token.content;
} else {
    console.error('CSRF token not found: https://laravel.com/docs/csrf#csrf-x-csrf-token');
}
```

my component call js file
```javascript 

 axios.get('/api/v1/ranking')
                    .then(function (resp) {
                        app.rankings = resp.data;
                    })
                    .catch(function (resp) {
                        console.log(resp);
                        alert("Could not load rankings");
                    });
```
api.php
```php

Route::group(['prefix' => '/v1', 'namespace' => null, 'as' => 'api.'], function () {
    Route::resource('ranking', 'Frontend\Seo\DomainRankingController', ['except' => ['create', 'edit']])->middleware('auth:api');
});

```

Response I get back: 

```
Request URL:http://127.0.0.1:8000/api/v1/ranking
Request Method:GET
Status Code:401 Unauthorized
Remote Address:127.0.0.1:8000
Referrer Policy:no-referrer-when-downgrade

{"message":"Unauthenticated."}

```

**Comment by bambamboole** [comment]
@LunarDevelopment I had no time to watch into this, but maybe I can tackle the issue the next days. 
Did you test this with admin@admin.com ?

**Comment by LunarDevelopment** [comment]
Thanks for updating me.

I did try this with admin@ and I still get the same error.

**Comment by bambamboole** [comment]
Okay I figured it out... When you use API Routes there is no session validation or cookie parsing. Thats why you are unauthenticated. Without Session you are not logged in.

To set up simple api authentication you need an column on the user table called api_token. You can fill it with a random string (maybe `str_random(60)` is enough). 
Then you have to hand over this api_token to you javascript (I repeated the csrf implementation) and set an additional header like this:
```
let apiToken = document.head.querySelector('meta[name="api-token"]');

if (apiToken) {
    window.axios.defaults.headers.common['Authorization'] = 'Bearer ' + apiToken.content;
}
```

thats all you need to be authenticated. When you use post requests you can add the token under the key **api_token** in the root of the payload.

When you just use this route to get data via ajax in the frontend, I recommend using a web route instead of an api route. 
If you really building an API I recommend studying packages like [laravel/passport](https://laravel.com/docs/5.5/passport) or [tymondesigns/jwt](https://github.com/tymondesigns/jwt-auth)

So this problem is not related to the laravel boilerplate. it's just not implemented in the boilerplate.

Hope I could help you with your issue :-)

**Comment by LunarDevelopment** [comment]
That was really insightful, thank you for taking the time to research and
enlighten me!

**Comment by bambamboole** [comment]
@LunarDevelopment can you please close the issue if it is resolved.
