### ISSUE TITLE
Work with 5.2?

### ISSUE THREAD

**Issue by MB34** [rappasoft/laravel-5-boilerplate#1103]
I have a requirement for using Laravel 5.2.45 due to the PHP version we have (5.6.28). Please don't berate me for not upgrading PHP versions as we have hundreds of thousands of lines of code that would need to be modified if upgrading PHP and we don't have time to do it now.

Anyway, Will this work for Laravel 5.2.45 or should I obtain an earlier release of the boilerplate?

**Comment by Shuyinsama** [comment]
Grab a earlier version. The 5.6 update was made for PHP7.1 I believe. At least 7

**Comment by rappasoft** [comment]
At that point you're putting yourself at risk, there has been plenty of security patches in this project as well as Laravel since that point. 5.2 is considered old, I understand about what you're saying with the project your working on. But it will only get worse the longer you wait.

<img width="819" alt="screen shot 2018-07-23 at 13 04 05" src="https://user-images.githubusercontent.com/6026504/43091758-f7571bf4-8e78-11e8-91e3-8829494455c9.png">

**Comment by MB34** [comment]
What release of the boilerplate should I download? The latest says it it is 5.17 and Legacy_5.4 is the oldest branch.
