### ISSUE TITLE
function script is defined in two files

### ISSUE THREAD

**Issue by rabol** [rappasoft/laravel-5-boilerplate#1233]
The function script is defined twice

one time in Global/HtmlHelper.php and one time in General/HtmlHelper.php

IMHO, there should only be one HtmlHelp class

**Comment by sitesense** [comment]
The actual HtmlHelper "class" only exists in Helpers/General/HtmlHelper.php

All of the files under Helpers/Global are autoloaded by the HelperServiceProvier so that they are available as global functions. So Helpers/Global/HtmlHelper.php is autoloaded and gives you global access to the HtmlHelper class functions.

Read Helpers/Global/_readme.txt for reference.

**Comment by rabol** [comment]
Well... there is a /appHelpers/Global/HtmlHelper.php and a /app/Helpers/HtmlHelper.php
