### ISSUE TITLE
Language selector does not localize Carbon

### ISSUE THREAD

**Issue by MisterMike** [rappasoft/laravel-5-boilerplate#131]
When switching languages, Carbon is not being updated with Carbon::setLocale($lang) or similar function to reflect language change.

Example: created and updated (diffForHumans ) timestamps in the view backend.access.index

**Comment by blomdahldaniel** [comment]
Carbon has its own sets of language packs. 
You can change this by adding `Carbon::setLocale('sv');` in the boot method in `App\Providers\AppServiceProvider.php`

But yeah, it would be nice to add a config for this. It cannot be the same abbreviation as in the Laravel language packages unfortunately.

Look in carbon docs to see the specifik language-code. The following will give diffForHumans() in Swedish.

I also change the php time-zone for the correct language such as moths, days and so on.
Just google php setlocale to find your own countrycode.

`setlocale(LC_TIME, "sv_SE");`
All and all It would look like this:
````
//App\Providers\AppServiceProvider.php

public function boot()
{
    setlocale(LC_TIME, "sv_SE");
    Carbon::setLocale('sv');
}
````

**Comment by MisterMike** [comment]
Thanks for your eloquent reply:) I thought it would be nice to also switch the Carbon locale when using the language selection menu in the header bar, but was unsuccessful with this.

    get('lang/{lang}', function($lang)
    {
        Carbon::setLocale($lang);

        session()->put('locale', $lang);
    
        return redirect()->back();
    });

**Comment by blomdahldaniel** [comment]
Hm.. I need some confirmation on this but I am not so sure that the `Carbon::setLocale($lang)` will remain outside of that clojure. Therefore it has no effect on your application.. That is why such logic should be placed inside of the AppServiceProvider so that it is set into all views every time.

You would have to do it differently with storing/retrieving  in session/cache/database and then pull that in to the AppServiceProvider I think. Or maybe get the url-stuff into the AppServiceProvider but I am not so sure if that would be a clean/nice way of doing it..

**Comment by blomdahldaniel** [comment]
@MisterMike did you get the answer you were looking for? In that case you may close this issue?

**Comment by MisterMike** [comment]
Issue closed. Thanks for your help!
