### ISSUE TITLE
composer install ErrorException 

### ISSUE THREAD

**Issue by hopewise** [rappasoft/laravel-5-boilerplate#136]
We've been working on release 1.3.5 then we made update to 1.6.8 release.
but we could not upgrade to 1.6.8

when we try to make composer install the following error appear :

    ErrorException in Model.php line 2695:
    Relationship method must return an object of type Illuminate\Database\Eloquent\Relations\Relation (View: C:\Users\afnan.k\Documents\l5\laravel-5 boilerplate\resources\views\frontend\klmon\js_permissions_variables.blade.php) (View: C:\Users\afnan.k\Documents\l5\laravel-5 boilerplate\resources\views\frontend\klmon\js_permissions_variables.blade.php) (View: C:\Users\afnan.k\Documents\l5\laravel-5 boilerplate\resources\views\frontend\klmon\js_permissions_variables.blade.php)

**Comment by rappasoft** [comment]
What is js_permissions_variables.blade.php?

**Comment by hopewise** [comment]
Its just use to read permissions from blade extensions and render them into javascript variables.
The problem is not in the file  js_permissions_variables.blade.php, we just don't know, but suspect the User model, as it has evolved..

**Comment by rappasoft** [comment]
Yeah there was a lot changed between those two versions, you can pm me and I can try to help, but it may be best to stick with the version you installed. Then in the near future start from scratch with the version you want. But that's just my suggestion. Unfortunately since this is a whole project and not a composer add on I can't push updates to everyone :(
