### ISSUE TITLE
Didn't understand, Why not `Public` and `Storage` folder part of the gitIgnore?

### ISSUE THREAD

**Issue by safoorsafdar** [rappasoft/laravel-5-boilerplate#154]
I didn't understand the public and Storage why not part of gitignore, its should add in. Reason is, storage contain lot's of cache, logs file(s) and also public updates automatically through gulp etc which I think not need to git.

**Comment by blomdahldaniel** [comment]
Inside `storage/logs` there is a `.gitignore` file that ignores all files except itself. That stays the same also for the `framework`, `app` directories. I think this comes as standard from Laravel.

##### Regarding `/public`:
Most often you don't want to even install the npm-dependencies on the server. You only run the `composer install` and then you are done. Since you most often never work directly on the server it is not necessary to have all the npm stuff. So, in development, Gulp makes sure that the files you need are placed inside the `/public` directory. The application can only access the files within `/public` so that is why Gulp is placing the files there.  So it would not make sense to ignore those files.

**Comment by safoorsafdar** [comment]
`storage` folder totally make sense to me now, 
but for `public` folder, if everything not handling from gulp or any build tool, what about if any images, uploads etc come across in future, we have to add in ignore file separately. and second thing is it's getting overload from `public` and `resource`  becuase if you talk about npm stuff they also exist in `resources` directory and `public` directory after build too. andl also if not using npm stuff, `resources` folder can be ignore not `public` but if you using npm stuff , you loading twice from `public` and `resources`. 

And if you not have any server to access/run gulp etc how you would able to run `composer` commands?

**Comment by blomdahldaniel** [comment]
Glad to hear that `storage` folder make sense, now its up for the explanation for public folder. :)

Okey, so all with npm, gulp and that, is used for developing (and developing is done locally on your computer). You need Gulp to take care of LESS/SASS and maybe browserify and versioning your styles/scripts. And you only have to do that in development. That is because, if you, in development copy the merged stylesheets to `/public/css` you dont have to use gulp on the server. 

I do not understand what you mean when you say `"we have to add in ignore file separately."`

the `/public` is always root for the website. That is why the index.php file is in /public.
Then it is a matter of security, the website (users of the website) is not supposed to access outside of the `/public` folder. Therefore all .js, .css and images is added to the `/public` so if you have images, you would store those inside `/public/img/picture.jpg` so from the view you can load the asset from `asset('img/picture.jpg')` since the `public` directory is the root directory. So, as you say, you want to load the css from the `/resources` that is not possible. The html shouldn't/cannot access outside of `/public`
#### The following is not possible
`````
<link media="all" type="text/css" rel="stylesheet" href="../resources/assets/css/app.css">
`````

So theoretically, you could instead manage all your css inside the `/public/css`. But the way laravel is structured, it keeps all the resources at one place, and allso, keeps all the LESS/SASS outside of the real-website since you cannot browse outside of  `/public`

The website is of course on a server, and in my case I had to install composer manually but the web hotel already had installed git for me. And to be able to run, just run, not manage or edit, a Laravel project, you dont have to use gulp on production as long as you have been using gulp on the development where you send all your css to `/public/css` (or to /build if you use versioning of your files.)

This is complicated but I hope that the different explanations make sense.
Read the [Laravel docs /structure](http://laravel.com/docs/5.1/structure)

**Comment by safoorsafdar** [comment]
Yeah exactly!!  I'm totally well aware about securities and application structure logic behind `resource` and `public` folder. And question logic still the same, let me explain it further.

`"we have to add an ignore file separately."` its means if you have images in your public it will also placed to git repository. its all right till images size not increasing as the theme. but as public directory is the root of the site, and any kind of images handling from user like Documents, User Avatars etc user related files, will also placed to `Public`. and these all files also will force to add in git repo until we ignore it (Of Course, as user increasing folder size get increase which you don't need to put to git. as per my understand).

Let me re-blunt my question:
- assets like css,js and themes related images all right to add to repo, but what about user related upload? which definitely goes to `public` and need to in ignore files.

- most important, I think git repo getting overload weather you handle from build tool or not. you only need to handle assets from single entry/pointer (`public` or `resources`) and simple way weather its handling from build tool or not, your assets should be in the single location weather its `development` or `production`. My only concern shouldn't repeat any kind of files in any form. So don't you think in this way assets like stylesheet and javascript can be available in another form like  less/sass and coffeescript on the repo?

**Comment by rappasoft** [comment]
I store my uploads in the storage folder under app. Just pull them from the storage folder where necessary, anything you store in public is indeed public, while user avatars might not be a big deal, if you have a password protected backend and you're storing files in the public folder, you can try to hide them with htaccess files and such, but there's still a way to get to them.

**Comment by safoorsafdar** [comment]
@rappasoft well, I think it's good idea to store such things into storage folder rather than public. How you access those document? `storage_path` can help but as described earlier not a good idea to access something outside of `public`.

**Comment by rappasoft** [comment]
I usually create a temporary download link to fetch it and request it on the frontend or backend.  Laravel has built in features to help. As for profile pictures I usually just use a gravatar helper but it would be the same process, though that's probably not the best route for those. 

Anthony Rappa

**Comment by blomdahldaniel** [comment]
@safoorsafdar that is some interesting thoughts of yours, avatar pictures and user-files. I have no experience with that but keeping it in the storage directory seems nice since it is not a part of the git repo and you also get the security. 

But to your second point i do not quite understand what you mean. For performance, it is always better to compile the sass/less code before, not on the server. Therefore yo have to compile the sass/less on development. Then, the duplication of files will occur when you compile `main.less` to `resources/css/main.css` and then you might want to combine multiple css files to have less http-requests for the user. So maybe in your elixir you run 
`````
.styles([main.css, fonts.css, specific-plugin.css], public/css/frontend.css)
`````
Then, those files are combined into `public/css/frontend.css`. And then if you use versioning of your files you need to keep the *origional* file that you later on send, versioned, to `/build`

So in my head, the slight duplication of files is necessary.

Have I understood your question right?

**Comment by rappasoft** [comment]
@safoorsafdar do you understand enough for us to close this? Trying to clear out the issues.

**Comment by safoorsafdar** [comment]
Yeah, All clear now, Thanks to everyone.

**Comment by rappasoft** [comment]
Awesome!
