### ISSUE TITLE
support for laravel 11?

### ISSUE THREAD

**Issue by alexteh** [rappasoft/laravel-5-boilerplate#1649]
# Before you create an issue make sure that:
- Your issue is **strictly related to the boilerplate** itself. Questions about Laravel in general belongs to the [laravel](http://laravel.io/forum) or [laracasts](https://laracasts.com/discuss/) forums.
- You have read the [documentation](https://laravel-boilerplate.com) thoroughly.
- You have searched for a similar issue among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.

# Be explicit
Try to be as explicit as you can when you ask anything.

**Comment by Azmeer-crescent** [comment]
No doubt this is one of the best Laravel templates out there. Awaiting v11 eargerly.

**Comment by RawZ06** [comment]
+1
I tried migrating to Laravel 11, but it’s really not easy. I’m considering rebuilding a Laravel 11 boilerplate, but I’m not sure since the current one is good.

Also, the frontend needs to be migrated to Vite and Vue 3, but that’s the easiest part, so to speak.

I already tested Laravel 9, but the 2FA library is dead, and I’m having compatibility issues with Spatie. In short, there are still two versions left to migrate.
