### ISSUE TITLE
Feature request: Full adminLTE integration (change auth views to AdminLTE auth views)

### ISSUE THREAD

**Issue by acacha** [rappasoft/laravel-5-boilerplate#18]
First of all congratulations for your work. Really amazing!

Maybe you will be interested in package:

https://github.com/acacha/adminlte-laravel

A Laravel package that switch default Laravel scaffolding/boilerplate to AdminLTE template including login/register/password recovery views.

As a Laravel Package it could be easily integrated in any Laravel project.

Kind Regards,

Sergi Tur

**Comment by rappasoft** [comment]
But the login/register/password views are part of the frontend, and the admin LTE theme is backend specific.

**Comment by acacha** [comment]
Ok I understand. Maybe is a matter of taste but when I've tested laravel-5-boilerplate it shocks to me ( and maybe only to me ;-)) that Login and register views are the laravel default ones and not AdminLTE. Maybe using AdminLTE look and feel i all views could give a more consistent graphical interface. 

Anyway your project is amazing with a lot of features I think i will use in near future.

**Comment by rappasoft** [comment]
I agree, I set it up to be two separate entities because usually the front facing website with all of those views is one look, and the backend is some sort of dashboard type looking entity, which is usually different. If they are the same in some other peoples cases it should be easy for them to convert.
