### ISSUE TITLE
using npm?

### ISSUE THREAD

**Issue by hopewise** [rappasoft/laravel-5-boilerplate#19]
This is not an issue, rather than development advice needed!
Can you please check up this question here: http://stackoverflow.com/questions/30350308/why-use-npm-with-laravel

**Comment by rappasoft** [comment]
The majority of reasons you probably see that is because Elixir (http://laravel.com/docs/5.0/elixir) downloads its dependencies from ```npm install``` which gives you that ```node modules``` folder, if you look inside there you will find elixir. This folder has no effect on the overall running of your application, in fact it is noted that you should .gitignore and not version this massive folder.
