### ISSUE TITLE
How to get avatar url for a user connected thru socialite

### ISSUE THREAD

**Issue by error500** [rappasoft/laravel-5-boilerplate#202]
In frontend/dashboard, the avatar comes from the picture attribute. This works fine for the connected user.
How can i display the avatar of a user that is connected with socialite (gravatar image uses the email and is not necessary the FB or twitter image) ?

**Comment by rappasoft** [comment]
In the new version it's just the gravatar associated with the email of the account. It does not switch it based on what is logged in because it would only be able to show it for the user locally, with gravatar you can show it for everyone globally if you were displaying users avatars to other users.
