### ISSUE TITLE
Locale on Carbon and date formats

### ISSUE THREAD

**Issue by error500** [rappasoft/laravel-5-boilerplate#211]
Hello
I don't know if the Carbon date for humans should works with current locale.... Is it a problem on my installation ?
setlocale(LC_TIME, 'fr_FR');

**Comment by Arrakeen** [comment]
You could use https://github.com/LaravelRUS/localized-carbon
However, the French translation is probably incomplete.

**Comment by blomdahldaniel** [comment]
Hm.. I am not sure how this has been solved before. One way to set the carbon locale is to put 
````
//will give swedish diffForHumans and time
    setlocale(LC_TIME, "sv_SE");
    date_default_timezone_set('CET');
    Carbon::setLocale('sv');

````
Inside the `Providers\AppServiceProvider`.

Not sure how it should be solved in this repo though

**Comment by petergit67** [comment]
Is this correct:

    public function boot()
    {
        setlocale(LC_TIME, "sv_SE");
        date_default_timezone_set('CET');
        Carbon::setLocale('sv');
    }

Works fine anyway.

**Comment by blomdahldaniel** [comment]
Yes, inside the boot method. I am sure @rappasoft will figure out a nice way to deal with this with his current language system.

**Comment by petergit67** [comment]
@blomdahldaniel are you working on an Swedish translation?

**Comment by blomdahldaniel** [comment]
@petergit67 ja just nu faktiskt, har kommit en liten bit iaf. Jag taggar dig i PR så kan du syna och ge förslag?

**Comment by rappasoft** [comment]
Jag förstod bara detta på grund av google :)

**Comment by petergit67** [comment]
Sorry we will not write in Swedish here. Daniel, could i have your mail so i can communicate in Swedish directly with you?

**Comment by blomdahldaniel** [comment]
Excuse me guys! Thought that it could be fun to write some swedish on github.. ;) Keeps rappa on his toes.. ;)

@petergit67 mail@blomdahldaniel.se

@rappasoft I have started to think that the `protected $languages` array needs to be different. I think that many different languages has multiple (often 2) names for the language. As in this example above, for us to get swedish in both php in general and in Carbon we need both the strings "sv_SE" and "sv"

So the `$languages` array in `\LocaleMiddleware` maybe has to bee different?
Something like this:
[ carbon-specific, php-language-code ]

Here is a list of Carbon language codes:
https://github.com/briannesbitt/Carbon/tree/master/src/Carbon/Lang

Here is a list of php/general locale codes
http://stackoverflow.com/questions/3191664/list-of-all-locales-and-their-short-codes

```
protected $languages = [
    ['en', 'en-US'],
    ['fr', 'fr-FR'],
    ['sv', 'sv-SE'],
];
```

I havent looked into hov you are using the middleware-array but I think that, in the long run, and also for both carbon and php locale we need to add both langage codes. Do you understand what I mean?

Thoughts?

**Comment by rappasoft** [comment]
Hmm yes, If I can figure this carbon thing out, I can probably make a lang config file with a multidimentional array and then just call the config file from the middlewares and anywhere else I need a lang code. Something like config('lang.php') config('lang.carbon'). I'm sure it will need more thought than that, but when in doubt, extract to config lol.

**Comment by blomdahldaniel** [comment]
Haha! xD "but when in doubt, extract to config" xD

Maybe call them `lang.carbonCode` and `lang.code` since the sv-SE and en-US in this case are standars, not just for php. (and also it would feel a bit confusing to have a line that says `config('lang.php')` haha!

**Comment by rappasoft** [comment]
So is it carbon that just isn't following the general language code standards?

**Comment by blomdahldaniel** [comment]
You are correct on that sir.. Kind of sloppy actually imo...

**Comment by rappasoft** [comment]
I also want to implement a timezone chooser in the profiles. Since it uses UTC by default, all timestamps are off for me, since I am America/New_York.

In my current projects I just do a getCreatedAtAttribute() function on my models and convert it, but that's annoying. Do you have this problem?

**Comment by blomdahldaniel** [comment]
Hm.. I understand. That should also be included i guess.. But how..? `config/TimeZone.php` ? lol xD

In Europe, specifically central Europe have the same time zone so that is not a big issue for us. Why do you need to set the timeZone for your project, isn't it possible to get the current time zone from the user? Cause I have a feeling that your need of a timezone chooser might be something that does not have to be inside this repo? Because it is not needed for all types of projects? Maybe create that as a compliment package repo that you suggest in [Suggested Packages](https://github.com/rappasoft/laravel-5-boilerplate/wiki/8.-Suggested-Packages) ? Or is it often a big deal for you in all your projects or just specific ones?

And, while we are on it. I do think that many projects could be very specific for a certain language. Therefore I would suggest a config ability to select what languages to add to the chooser and then if only one language is selected, the whole choosing system doesn't show.
Thoughts?

**Comment by rappasoft** [comment]
Because all of my timestamps are 5 hours ahead unless I convert them. It's kind of annoying.

**Comment by blomdahldaniel** [comment]
Okey, then thats a thing. But in that case I would also like the ability to select only one and then not show any other alternatives, not even the button.

**Comment by rappasoft** [comment]
You mean lock everyone to a certain timezone?

**Comment by blomdahldaniel** [comment]
exactly, because if a European would use this boilerplate for a cause that only directs to users within the country, it would make no sense to have the ability to either switch language or time zone.

**Comment by rappasoft** [comment]
Ah yes I see, I will have to research the best way.

**Comment by blomdahldaniel** [comment]
Awesome! :+1:

**Comment by blomdahldaniel** [comment]
@error500 sorry for clustering up your issue with talk about other stuff. Did the example inside the **boot** method in `Providers\AppServiceProvider` work?

**Comment by error500** [comment]
Effectively, this works. I also added `Carbon::setToStringFormat('d/m/Y');`
```
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Carbon\Carbon;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     * Set Carbon defaults
     * @return void
     */
    public function boot()
    {
        setlocale(LC_TIME, app()->getLocale());
        date_default_timezone_set('CET');
        Carbon::setLocale('fr'); // app()->getDateFormat() ??
        Carbon::setToStringFormat('d/m/Y');
    }
```


But this is a good solution for a "one lang/one time zone application". This is my case. But for the boilerplate it could be nice to have 

in .env
`TIMEZONE_FALLBACK=CET`
`DATE_FORMAT_FALLBACK=d/m/Y`
`DATETIME_FORMAT_FALLBACK=d/m/Y xxxx`

And in user profile, the ability to change to another timezone for a user with a selector. So th timezone comes either from his specific choice or as default from the fallback.

For Carbon locale, simply use the  ISO-639 locale code extracted from the language choosed by the user. Pass trough a locale table ?

['language'=> 'fr_FR','date_format'=>'fr'],
['language'=> 'es_ES','date_format'=>'es'],
['language'=> 'es_AR','date_format'=>'es'],

**Comment by blomdahldaniel** [comment]
Yes like you said, using the `boot()` method within the `AppServiceProvider` is more likely to be a "one language/time zone application".

Look att my PR #233 where the localization of the dates is solved through the LocaleMiddleware.

I think that @rappasoft is looking for a solution for time zones right now.

I think you have a good idea regarding the the timezone and the user. That the user can set the time zone together with the profile settings. Maybe, for a loged in user, even language selection should be set within the profile settings? No need for the user to have the ability to change language "all the time" from the nav-bar. The more I think about it, it doesn't make sense to have the language selector in the nav-bar.  Maybe its fine for the frontend part but certainly not in the backend area?

I am not so sure about adding the new variables to the `.env` though. But when needed I think that using a locale `config` file would be better in that case. Inside the `config/localization.php`, one could manage:
* Language array, comment out languages that should not be used. (If only one language is in the array, no selection can be made for the user. That is then the default language)
* TIme zone (the same right here, select the wanted time zones and if there is only one timezone in the array, no selection can be made.)
* Maybe date format, if that is a big thing. (@error500 why do you think this is necessary? Why set a standard instead of specifying that within the controller or inside the view? I would feel limited with the date format set in the config.)

**Comment by error500** [comment]
Hi Daniel,
About setting a standard instead of a specific in a view :
A UK user will like to see a date in `m-d-Y` format but for the same screen, a french one will prefer `d/m/y`

Also : I had a look at #233 

About the language selector. Remind that you will not be able to store the language for a guest user since he doesn't have any database storage. So the selector could disapear when connected and could be choseen in the "profile" settings, (with a timezone selector ?)

**Comment by blomdahldaniel** [comment]
Great point about the date formats! That should maybe also be included in the `LocaleMiddleware` then! :)

For users the language can be set through session or cookie. And for the loged in user it could also be session or cookie but could be included in the users table as well. I do not know which should be the better one. It will be a lot more complicated to set the value in the database since it then has to be a default value. And that value has to be adaptable if, in the config, only one language is set. Nothing that is hard to do but increases the complexity of the system.

**Comment by rappasoft** [comment]
Merged in locale stuff from other issue, will cover date formats and timezones next.
