### ISSUE TITLE
Missing translation for crud button tooltip at /users/deleted

### ISSUE THREAD

**Issue by blomdahldaniel** [rappasoft/laravel-5-boilerplate#223]
I think that there might be a missing pointer in the crud button at `/admin/access/users/deleted`
I am not sure but it seems like it is just forgotten completely in the translation files? It should be in `/buttons.php` ?

<img width="1048" alt="skarmavbild 2016-01-07 kl 00 55 53" src="https://cloud.githubusercontent.com/assets/10044093/12158372/b24f0cfe-b4d9-11e5-9675-8bb951e96a55.png">

**Comment by rappasoft** [comment]
Hmm I don't have a computer in front of me but theres a good chance I forgot because that's the path to the old trans file.

**Comment by blomdahldaniel** [comment]
:+1: yep, I see if I can make a quick PR on this. I take the translations from the old project.

**Comment by rappasoft** [comment]
Pulled and did some other stuff for you here: https://github.com/rappasoft/laravel-5-boilerplate/commit/94e176348461bc33f68e33dd464f02f9539ed4dc

That popup alert is called Sweet Alert (http://t4t5.github.io/sweetalert/) which isn't good as a replacement for confirm boxes, and should really be used for forms. 

But I hacked it in to work as a confirm box, it's still secure because:

1. Those 2 buttons only show up if the users have the right permission.
2. Even if the user somehow clicked the link through javascript, the sweet alert calls are wrapped in @permission tags.
3. If they get around that, on the server side the request classes for each URL check the permission for a third time before firing the correct code.

So still secure!

**Comment by blomdahldaniel** [comment]
Sweet Alert, thats the name. Thanks.

Beautiful solution i must say, love the thorough security work!

So I just ad a new couple of lines to my swedish translation-files then. :)
