### ISSUE TITLE
Add support for Multitenancy

### ISSUE THREAD

**Issue by kdhana** [rappasoft/laravel-5-boilerplate#238]
https://msdn.microsoft.com/en-us/library/aa479086.aspx

**Comment by blomdahldaniel** [comment]
**Do you want it for the boilerplate itself?** So that all updates could be spread to all the users? That would not make sense since this is supposed to be a boilerplate. Something where you build further on your own.

**Or do you want this for yourself in your own project?**
I then suggest that you take a look at: [https://github.com/hyn/multi-tenant](https://github.com/hyn/multi-tenant). I am not sure what @rappasoft thinks here but I sense that this would be something too specific for this boilerplate. So this would be something you would have to go on and do on your own. So simply do your own fork of this?

**Comment by kdhana** [comment]
I am aware of https://github.com/hyn/multi-tenant but was unsure to propose it.
Personally i don't need this in PHP, but looking for multi-tenancy in asp.net boilerplate projects i just thought this feature/ functionality might be useful for a lot of people.

**Comment by vjandrea** [comment]
@kdhana i agree with @blomdahldaniel, maybe we could set up a poll but i feel that the vast majority of those who are fork and clone this repo don't need multitenancy every day.

**Comment by rappasoft** [comment]
Yeah many people including myself probably use this for things such as business backends or personal projects. Though its useful for any size, and would still be useful if you wanted multi-tenancy, you would just have to alter it yourself.
