### ISSUE TITLE
Sort and filtering

### ISSUE THREAD

**Issue by petergit67** [rappasoft/laravel-5-boilerplate#267]
I think it would be great with sort and filtering especially on Permissions as the page can grow in items.

This is how i done in my projects handling:

![skarmavbild 2016-01-31 kl 11 23 47](https://cloud.githubusercontent.com/assets/6569136/12701587/b53b0e58-c80d-11e5-8e9e-55391ac96bfa.png)

- the ability to check one or more items for mass functions like destroy and unlock

- the ability to open and close an filter section under buttons

- the ability to reset all filters and sort to pre defined default

- the ability to sort by each column

- all changes in sort and filter are posted and saved i an session to preserve state even if user jumps to other sections and after editing/editing an item

In mobile view the button text are hidden as well as some table columns to get better user experience:
 
![skarmavbild 2016-01-31 kl 11 38 25](https://cloud.githubusercontent.com/assets/6569136/12701636/425e09f6-c80f-11e5-9673-c56ffeb640db.png)

Any thoughts?

**Comment by blomdahldaniel** [comment]
I like the way of being able to handle multiple rows at once. And the filtering is nice too. How have you implemented this? We are looking for a neat way of dealing with it that is scalable and don't need specific config if you want to customize it. So something like [DataTables](http://datatables.net/) would be nice. You dont have to create your own logic. I think both rappa and I are trying to wrap our head around this.

Regarding the mobile version, I do not think you should hide columns for mobile. Maybe in some specific cases but not in general. Instead use bootstrap table-responsive. You should not have to lack data just because you are in mobile.

**Comment by rappasoft** [comment]
Datatables responsive stuff does some cool column folding with plus and minus icons and stuff.

**Comment by petergit67** [comment]
I will be happy do give you the code for my project handling so you can look at it, i am sure i haven't done this in the most accurate way but it might give you some ideas?

I have tried DataTables and it is great i some ways but to achieve what my customers demand i have to go beyond DataTables. 

But this is outside the actual BP code, in BP i think DataTables would work fine in permissions table where an simple sort en search would be sufficient.

**Comment by blomdahldaniel** [comment]
I am going to close this issue for now. Filtering of users and stuff is on the future to do list.
