### ISSUE TITLE
Hardcoded text in UserAttribute.php

### ISSUE THREAD

**Issue by steenrabol** [rappasoft/laravel-5-boilerplate#268]
Hi

there is hardcoded text in the file: app/Model/Access/User/Traits/Attribute/UserAttribute.php line 34 ('yes') and line 35 ('No')

**Comment by poseso** [comment]
resources/lang/en/buttons.php
resources/lang/es/buttons.php etc..

    'general' => [
        'cancel' => 'Cancel',
        'yes' => 'Yes',
        'no' => 'No',

then on app/Model/Access/User/Traits/Attribute/UserAttribute.php line 31

    public function getConfirmedLabelAttribute()
    {
        $Yes = trans('buttons.general.yes');
        $No = trans('buttons.general.no');
        if ($this->isConfirmed())
            return "<label class='label label-success'> $Yes </label>";
        return "<label class='label label-danger'> $No </label>";
    }

that work for me

**Comment by steenrabol** [comment]
Hi

I can also make it work by fixing the template, but my point is that if it get fix, then nobody needs to correct it manually when using none English language 

I discovered the error while testing my Danish translation

**Comment by poseso** [comment]
then you saw the same problem in admin/access/roles     All and none is also not working

**Comment by blomdahldaniel** [comment]
Great findings @poseso I am also glad to hear that we have some more Scandinavian people in here. ;)

I do not understand what yo mean with:
> I can also make it work by fixing the template, but my point is that if it get fix, then nobody needs to correct it manually when using none English language

I am gonna lable this issue with "bug" as of now and take a look at it.

**Comment by poseso** [comment]
/admin/access/users    -> Other Permissions   same (none)
/admin/access/users/create  -> Associated Roles   on Administrator and User  the word Show is also not working  but it's kind of different since when you change language to spanish it says Mostrar Permisos as it should but if you click on it change to hide/show Permisos.

same for /admin/access/roles/create where it should say on associated permissions where it says All and Custom it spanish at least should be Todos and Personalizado.

and /admin/access/roles/permissions/create   on Group it also says (none) and System? its also not working.

That's all i can see :P

**Comment by blomdahldaniel** [comment]
@poseso  The problem of `None` is that the spanish translation has `'none' => 'None'` in its translation.
What should it be in Spanish?

I think I have done all of the litle bugs otherwise. Please correct me if I am wrong. :)

* ~~UserAttribute.php~~
* ~~PermissionAttribute.php~~
* ~~`/admin/access/roles/create`~~
* ~~`/admin/access/users` -> Other Permissions~~
* ~~`/admin/access/users/create` toggle Show/Hide link~~
* `/admin/access/roles/permissions/create` does already work but lack Spanish translation. What should it be @poseso ?

**Comment by poseso** [comment]
none  =  Ningúno

**Comment by poseso** [comment]
/admin/access/users/2/edit     <-    on associated roles   in administrator and user there is the same prob with trans with (show permissions)

**Comment by blomdahldaniel** [comment]
I think all of the issues that have come up in this thread now is fixed.
Thank you @steenrabol and @poseso

**Comment by poseso** [comment]
resources\lang\es\validation.php Line 124

'system' => 'Sistema?',
