### ISSUE TITLE
[Question] Using L5 Boilerplate for a new project

### ISSUE THREAD

**Issue by jarod51** [rappasoft/laravel-5-boilerplate#277]
Hi

I would like to know if using L5 Boilerplate for a new project will avoid me to obtain new updates. I mean if i start adding my own stuff (develop and master) i won't be able to apply your latest updates right ?

Best

**Comment by ninjaparade** [comment]
@jarod51 you can add an `upstream` remote for your repo and pull in the changes from this repo.
You'll have to read the wiki to see what's changed and you'll have to resolve conflicts.

I currently do this with 3 projects, it takes some time every once in a while but its well worth it.

**Comment by error500** [comment]
I did also some upstream fetch & merge on a project.
I tried to separate my routes, user model management and all folders to facilitate merging

**Comment by blomdahldaniel** [comment]
I actually just took one version and stuck with it. I made some changes when I saw that great features came and when security buggs was fixed. So in some ways I think it might be ok to do so as well. I guess the best option is to keep an eye of what is going on.

**Comment by rappasoft** [comment]
Upstream seems interesting, currently no way to keep it updated on a daily basis instead of manually checking, since nothing is extracted as a composer project. Doing so in my opinion would defeat the purpose, as you would be stuck to my code.

It's more of a download and install and go from there, project.
