### ISSUE TITLE
Eloquent vs Query Builder

### ISSUE THREAD

**Issue by petergit67** [rappasoft/laravel-5-boilerplate#282]
Just curious, why use Eloquent over Query Builder?

**Comment by daniel-farina** [comment]
Eloquent will save you a lot of time. 

I'm learning Eager Loading now and I really like it. 

		$lead = Leads::
		findOrFail($id)->
		where('id', '=', $id)
			->with('items')
			->with('items.product')
			->with('customer')
			->get();

This will get me an object that includes the  parent and children data of the lead. As you can see there I'm getting the leads with items/item's details (products), customer that the lead belongs to, etc. Instead of writing long queries and inner joins. 
`[
    {
        "id": 9,
        "status": "1",
        "am_customer_id": 3,
        "am_store_id": 1,
        "first_name": "Daniel",
        "last_name": "Farina",
        "address": "2547",
        "notes": "ggfgfhghf",
        "created_at": "2016-02-08 08:22:47",
        "updated_at": "2016-02-08 08:22:47",
        "items": [
            {
                "id": 19,
                "am_lead_id": 9,
                "am_product_id": 2,
                "details": "xxxx",
                "created_at": "2016-02-08 08:23:11",
                "updated_at": "2016-02-08 08:23:11",
                "product": {
                    "id": 2,
                    "name": "Small Digital Sign",
                    "am_category_id": 1,
                    "description": "Small product",
                    "price": "80.99",
                    "created_at": "2016-02-07 18:28:55",
                    "updated_at": "-0001-11-30 00:00:00"
                }
            },
            {
                "id": 20,
                "am_lead_id": 9,
                "am_product_id": 2,
                "details": "cccc",
                "created_at": "2016-02-08 08:23:11",
                "updated_at": "2016-02-08 08:23:11",
                "product": {
                    "id": 2,
                    "name": "Small Digital Sign",
                    "am_category_id": 1,
                    "description": "large product",
                    "price": "80.99",
                    "created_at": "2016-02-07 18:28:55",
                    "updated_at": "-0001-11-30 00:00:00"
                }
            }
        ],
        "customer": {
            "id": 3,
            "status": "1",
            "am_store_id": 1,
            "first_name": "Mario",
            "last_name": "Brother",
            "phone": "4104194508",
            "email": "",
            "address_1": "",
            "address_2": "",
            "created_at": "2016-02-08 04:03:02",
            "updated_at": "2016-02-08 04:03:02"
        }
    }
]`



**Eloquent is amazing but you must:**
*setup a relational database 
* create the relation in your migrations
* Make sure you start with the child when creating the dropping functions in your migration else you will get a bunch of error swhen you run migrations. 
Same goes when create tables, start with the parent and then the children ,elese you will with foreign key errors. 
*let laravel know about  the foreign keys in your models. 

Awesome video about Eloquent Relationships:
[](https://laracasts.com/series/laravel-5-fundamentals/episodes/14)

**Comment by petergit67** [comment]
You made my day Dan, thank you.

This is exactly what i am trying to do. Performance wise i heard Eager Loading it the way to go.

**Comment by rappasoft** [comment]
Eloquent and query builder are very similar, query builder gives you much more control, but eloquent has a much neater syntax. I use Eloquent for simple queries and scopes and eager loading, and query builder for more complex joins and control over different items.

Also, depending on which you use, they can return different things, collections, arrays, collections of collections, etc.

**Comment by petergit67** [comment]
if i want to use query builder do i have to change a lot of code/structure in your BP?

I noticed that if i changed do query builder my index.blade.php broke on count and render functions.

**Comment by petergit67** [comment]
Do you have query builder somewhere in the BP?

**Comment by rappasoft** [comment]
Count and paginate should work the same on both:

```
return User::paginate(50);
```

```
return DB::table('users')->paginate(50);
```

**Comment by daniel-farina** [comment]
I agree for complex syntax query builder is the way to go but for simple crud pages thne eloquent is great. 

@rappasoft 
Thank you for creating this collection. It has been very helpful. It really helped me get into Laravel.

**Comment by blomdahldaniel** [comment]
I am going to close this issue as of now. Hope you found your way @petergit67.
