### ISSUE TITLE
Prevent multiple submits on form

### ISSUE THREAD

**Issue by petergit67** [rappasoft/laravel-5-boilerplate#283]
Is there a way in Laravel to disable the submit button until the form is processed?

**Comment by blomdahldaniel** [comment]
Peter, I think that the [Laravel forum](http://laravel.io/forum) or [Laracasts Forum](https://laracasts.com/discuss) is more suited for this question. That could also be the case for a couple of other questions here at this repo. Both me and @rappasoft will try to keep the iessues on this repo more strict about issues regarding this project from now on. It is a lot to maintain if we would keep on allowing non repo related questions all the time.

To give a pointer to your question, I do not fully understand what you mean but I think what you seek could be done through javascript. I have come across that I often got multiple entries in the DB. This was because of users (often on mobile or at stations with bad internet connection) who clicked multiple times on the submit button.

I suggest that you add simple javascript to disable the button after the first click. At least that did it for me. In some special cases I actually also added a check method in the DB for newly added items and then checked if the incoming request was a duplicate.
