### ISSUE TITLE
Thoughts about adding multi language support for Eloquent 

### ISSUE THREAD

**Issue by pebbo** [rappasoft/laravel-5-boilerplate#290]
Hi all,

first of all, please excuse that this text is more a discussion topic than a real issue with the boilerplate project, but I did not know where to put this instead of here.

Would anybody else like the idea to have a possibility to get localized fields from the database depending on current locale (with fallback)? I am currently working on a solution for a project of mine and thought that this would be pretty nice to have it as part of this wonderful boilerplate project.

Anybody some thoughts about that? There are some projects at github regarding this issue but I am currently not sure, which one would be best to be included or if it may be the best idea to create a new one as part of this project.

For example, maybe this one would fit: https://github.com/dimsav/laravel-translatable ?

Regards,
pebbo

**Comment by blomdahldaniel** [comment]
This is a pretty neat idea. But where should it be applied to this project?
Is it for the permissions and roles?

**Comment by PReimers** [comment]
Permissions and roles would be a good start.
If the project gets more tables with "localized data" they should use it to.

**Comment by pebbo** [comment]
I think this is a good idea and will see what I can do.

**Comment by blomdahldaniel** [comment]
Glad to hear that you will take a look into it. **I just want to give a possible heads up** that this could be the type of thing that maybe should end up being a suggested plugin and not included in the main repository.

One of the reasons to that is that a lot of times it is seen as best practice to write code in English. Especially when using a framework like Laravel where it forces you to use English. Because when using Laravel and then use localized stuff as well, you end up with a code base that has mixed localizations. That is a lot of times not preferable and not seen as best practice. 

So, it is nice that you want to contribute but I think that the feature might only be suggested as a plugin and note merged in to the project because of:
  1. Make things over-complicated
  1. I don't think that there is enough people who need this to be a default feature
  1. It breaks best practice of using only one language in your code base.

**Comment by blomdahldaniel** [comment]
I am going to close this issue now. Reopen if you think it is necessary.
