### ISSUE TITLE
Import Admin LTE as LESS

### ISSUE THREAD

**Issue by vpratfr** [rappasoft/laravel-5-boilerplate#302]
Would be nice to have adminlte as less files (or scss but I think they only have LESS currently).

This would allow simply (un)-commenting whichever components are (not) required.

**Comment by rappasoft** [comment]
The old version was LESS, we switched to strictly SCSS.

**Comment by vpratfr** [comment]
So you have all features from adminlte ? Or just part of it? Like graphs, all widgets, ...?

**Comment by rappasoft** [comment]
It still has the full app.js file so that functionality should still be there.

All the scss files are just ports of the original less files so all of that should be the same.

If you want the legacy 5.1 version has the less files: https://github.com/rappasoft/laravel-5-boilerplate/tree/Legacy_5.1/resources/assets/less/backend

**Comment by vpratfr** [comment]
Ok great
