### ISSUE TITLE
Datatables 

### ISSUE THREAD

**Issue by nasirkhan** [rappasoft/laravel-5-boilerplate#325]
Do you have any plan to integrate the 'Datatables' with the server side support (https://github.com/yajra/laravel-datatables) in boilerplate? did you earlier tried to do so?

Whenever i create a new index page it requires me to implement a search to find the stored records. In most of the cases i think it can be solved using Datatables Ajax implementation.

**Comment by blomdahldaniel** [comment]
Yes this has been a big topic. In some ways this would be flat out awesome. In some ways it will make things a bit more complex. I am not so sure of what I think actually. In some ways we need to keep this boilerplate as a boilerplate. It cannot be a ready to use product because that is not what it is and everybody has different needs.

Anyhow, I think that an implementation för the backend access-management would be good and okay but under strict conditions. We would have to create very precise documentation and really figure out the best scalable way that still makes it easy for the *noob* to handle.. So yes, this is a big question and possibly a big and important task.

**Comment by rappasoft** [comment]
I have implemented this package in this boilerplate before, it is very nice, but is also a little buggy and I don't really like the way you have to do it. But regardless I might use it in the next version in the access section.

**Comment by nasirkhan** [comment]
I do not think it is that complex. I integrated this package in one of my project and it is perfect. The best part if the ajax search, sort. You will need the search feature if the number of database records started to increase. 

If you think that it is not appropriate to include this feature, then what is your suggestion about the search?

**Comment by blomdahldaniel** [comment]
A solution for this feature is on the to-do list for the project so I will close this issue now. The feature will be added when someone has the time to integrate it.
