### ISSUE TITLE
Vuejs

### ISSUE THREAD

**Issue by Francismori7** [rappasoft/laravel-5-boilerplate#406]
Since most people prefer vuejs now in the Laravel community, I think we should convert this project to vuejs. I'll be making it on my own and submit a PR.

**Comment by rappasoft** [comment]
Yeah but not everyone will prefer it, for example, I won't. I looked into it but I still don't know anything about it.

**Comment by Francismori7** [comment]
That is true. I might maintain a fork then.

**Comment by digitalit** [comment]
Please make an Vuejs version @Francismori7

**Comment by Francismori7** [comment]
This may take some time because this is quite a complex jquery project.

**Comment by rappasoft** [comment]
I can probably install vue and maybe convert the dashboard but the entire thing would be overkill, I don't know how many people are familiar with it, i'm not.

**Comment by Francismori7** [comment]
I'll see what I can do; it's certainly the most popular framework in the community now although not everyone has made the switch.

**Comment by digitalit** [comment]
I am a bit confused about the whole Vuejs thing since everyone talked about having Laravel for backend and Vuejs for frontend.

In my world backend is the admin part and frontend is the homepage that customers see but that was not what they meant. 

Laravel should do everything on the server-side and Vuejs everything on the client-side.

Still not sure about all this but it is mentioned in many places.

Maybe you can shed some light?

**Comment by Francismori7** [comment]
Vuejs is your "browser side" JavaScript framework. Laravel is server side
with PHP.

Le ven. 8 juil. 2016 10:29, Peter Carlsson <notifications@github.com> a
écrit :

**Comment by moreli** [comment]
If you are starting a branch for Vue i'll be interested in contributing.

**Comment by blomdahldaniel** [comment]
I think Vue is awesome. It allows us to create great user experiences. And with the whole component and vueify stuffs its just great. But I must say that I don't quit understand the need to implement it to this? Is it because your own admin-panels are super-big and need a lot of Vue...? Guess it all depends on what your building.

@digitalit vue is the layer you would like to add if you, for example, want to make slick user experience where the browser doesnt refresh and stuff like that. Make sense for cases like web-shops when you add a product you dont want the browser to reload afterwards but you maybe want to store the products in a session or cookie from the backend stuff. Of course this could be done with plain jQuery ajax but Vue givs so much  more. Just take a look att the first episodes of Jeffrey Ways free turorial on laracasts: [vuecasts.com](http://vuecasts.com)


But soon Vue 2.0 will be upon us and that will change quit a lot..

**Comment by SuperlativeEntity** [comment]
You could probably achieve the same result using pjax (loading views and keeping push state) and normal jquery ajax (posts, gets etc.)

Couple this with a paid solution like Kendo UI and you're good to go. (Yes, I know it's not open source, but it's too good not to mention)

**Comment by pappu687** [comment]
I don't see a point why the entire project would need Vue integration. This boilerplate is not SPA, is it ?

**Comment by SuperlativeEntity** [comment]
I agree with @pappu687, it would make more sense to rather implement JWT and set up routes in the api middleware group. A separate Vue SPA project can then be created to consume the api with token authentication.
