### ISSUE TITLE
Question About Permission.

### ISSUE THREAD

**Issue by viralsolani** [rappasoft/laravel-5-boilerplate#475]
I think permissions and permission group module are very helpful as It is really helpful to authorize each request. 

Is there any particular reason to remove permission module ? how can we add permission now ?

Could you please explain in brief?

**Comment by syardumi** [comment]
I agree. I was thoroughly confused when I saw that the permission page is now gone. What gives?

**Comment by poseso** [comment]
I also like the permissions but under the roles, so I can create roles with specific permissions, I find it more clean, the way i have it with the master branch is that i create a Role then i assign that role permissions (create,read,update,delete) for each module i have,  module Customers(Create and Read)  Module Invoice(Create, Read, Update), admin has it all etc.. so every role has specific permissions

**Comment by rappasoft** [comment]
The permissions never dissappeared, only the GUI for it did. You can still do everything with the app before that was gone. It was removed because it was a lot of extra code, js, and views that were unneeded. You shouldn't be doing CRUD operations on permissions at runtime because they will never change when they're called in the code.

That's why you have roles, so you can modify those without touching the permissions and still be as granular with it as you want.

**Comment by mikimaine** [comment]
how can i add ? should i add permissions to the database manually ? or with db seed?

sorry you have answered it , but i didn't get it .

**Comment by rappasoft** [comment]
You should manage your permissions in the seeder.
