### ISSUE TITLE
5.3 Update

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-5-boilerplate#485]
Been working on a ground up since 5.3 came out. Much more changed than I thought. Probably about 30% done.

Will keep everyone posted.

**Comment by digitalit** [comment]
Keep up the great work. It is much appreciated @rappasoft  :)

**Comment by AlehDev** [comment]
I've been transferred to version 5.3. Later we can compare.

**Comment by rappasoft** [comment]
I've started with a fresh 5.3 install. It is very much different so far. It wasn't as easy as dragging all of the folders over unfortunately.

**Comment by pebbo** [comment]
Currently working on adding translatable to the roles and permissions... do you think I should wait until the 5.3 boilerplate update is ready?

**Comment by rappasoft** [comment]
It's all coming together nicely, complete with new Laravel features:

<img width="1021" alt="screen shot 2016-09-23 at 11 44 41" src="https://cloud.githubusercontent.com/assets/6026504/18792094/3081f9e4-8183-11e6-9802-7aee578664fd.png">

**Comment by poseso** [comment]
nice!

**Comment by chemitaxis** [comment]
Thank you so much for your work...

**Comment by LunarDevelopment** [comment]
Dare you give an ETA?

Amazing work so far by the way, Thankyou very much.

**Comment by rappasoft** [comment]
Have a feeling this one is going to be V4 because it's changed way too much for me to not justify it.

Hoping a week or two max.

**Comment by blomdahldaniel** [comment]
Thats so awesome!!

**Comment by poseso** [comment]
that's great!

**Comment by digitalit** [comment]
Anyone knows how this would work upgrade-wise: laravelshift.com

**Comment by rappasoft** [comment]
Got stuck on the stupidest of problems, back on track just lost a few days.

**Comment by rappasoft** [comment]
Since Vue 2.0 came out, I have to figure out what I need to change upgrade now. Bad timing.

**Comment by blomdahldaniel** [comment]
Haha! :) That timing! Looking forward to see your work!

**Comment by rappasoft** [comment]
Vue 2.0 working. BTW i'll get to the issues and PR's within this release. So when it launches i don't have to merge anything and will probably close it all.

It's getting there. Haven't had time the last couple days. But I dramatically simplified things.

I'll put it on development when i'm satisfied, but will need more eyes before I release.

**Comment by minedun6** [comment]
is it possible to make something so that we can understand how to integrate another theme ? let's say metronic theme maybe or any other bootstrap theme ^^.
Something else, sometimes when i submit a form, it logs me out even when I am on admin. The login area doesn't show the error message sometimes ^^. Last thing is that this package needs some serious documentation since it's getting more and more attention.

Keep it up my friend.

**Comment by rappasoft** [comment]
If anyone wants to try what I have so far it is on development: https://github.com/rappasoft/laravel-5-boilerplate/tree/development

Right now everything works, but I've yet to refactor some things and do all of the issues and pull requests.

**Comment by activemonkeys** [comment]
Thank you Anthony. Just got it up and running and was able to login (after db:seed) with admin@admin.com. So far so good.

**Comment by rappasoft** [comment]
Cool let me know what you think.

**Comment by poseso** [comment]
I just tried it, everything is working smoothly, just seen a minor typo when permantely delete a user in the sweet alert, but everything else is working correctly

**Comment by brentkozjak** [comment]
Looks good!  Just tinkering with the access management - when I disable a user, I can't re-enable them.  They simple don't appear on the list almost as if they have been deleted.

**Comment by rappasoft** [comment]
They're not in the deactivated section?

**Comment by brentkozjak** [comment]
My bad, didn't notice that section!  Works fine, please ignore.

**Comment by rappasoft** [comment]
I'll modify where it routes you depending on selection to avoid confusion.

**Comment by activemonkeys** [comment]
Just one minor thing I came across so far

Log Viewer - viewing the log data for a certain date - when pressing "All" -> InvalidArgumentException in compiled.php line 9541: Route [log-viewer::logs.show] not defined.

Furthermore it seems to be working smoothly. Within the coming days I'll start a new test project. Will let you know when I come across other things. 

As for the AdminLTE theme. In the demo on https://almsaeedstudio.com/ you'll see that all menu items have an icon in front of them and these icons remain visible when the sidebar is closed. No problem to implement this functionality myself. However, it would be nice when it's part of your the boiler plate. 

Thanks for all your work so far. This really is a time saver. Especially the clear split between frontend/backend is much appreciated!

**Comment by daniel-farina** [comment]
Keep up the great work, this is the bet way to get started with Laravel, period.

Dan

**Comment by rappasoft** [comment]
@activemonkeys Good idea I never even noticed, I added the icons and the mini-sidebar feature. Still trying to figure out the log viewer thing.

**Comment by activemonkeys** [comment]
Thanks for implementing the icons and mini-sidebar feature Anthony! Much appreciated. 

Ran into another minor issue: 

app\Http\Middleware\RedirectIfAuthenticated.php

it says: 

    if (Auth::guard($guard)->check()) {
            return redirect('/home');

However /home is an undefined route

**Comment by num3thod** [comment]
@activemonkeys So in other words, your test app is...homeless?

Good catch. Should be `('/')` I guess. Or whatever your specific app requires.

**Comment by activemonkeys** [comment]
@num3thod yes, my app is looking for shelter!  Changed it also to ('/'). For other users however, it would be nice when it's corrected in the boiler plate. 

Also I noticed when the (new) Dutch language is selected the word "Language" remains visible in the selector. The Dutch word for "Language" is "Taal". Would be nice when this is corrected too, should there be any Dutch users..

**Comment by num3thod** [comment]
Agree completely

**Comment by rappasoft** [comment]
I took the dutch pack from the open pull requests, I don't speak it, but I didn't look through the translations. Looking through it there's many lines that were not translated from english.

Good catch on the middleware route.

**Comment by blomdahldaniel** [comment]
**This seems great!**

Suggestions, (i can fix it myself but want to hear what you think).

1. Remove "Change Password" from `frontend/includes/nav.blade.php`. It feels neither necessary nor common to have such a link directly from the navbar.
2. Change name of the "dashboard" to something more like "My profile". So in moth the navbar and in the routes instead use the term **profile**. In my head, that would feel more easy to understand and more like other applications.

Thoughts?

I will go over the Swedish translations as soon as this reaches a more stable stage. :)

**Comment by rappasoft** [comment]
1. Yeah I don't know why that's been there since day 1.
2. I agree, but I also envisioned that gaining more tabs that interacted with the backend app, and it acting as the users dashboard for managing the app, just like the admin section is the dashboard for administrating the app. But I guess Profile has the same meaning. I may be old school but profile used to just be like your name and bio and stuff. Maybe we rename the tab in the dashboard to My Profile?
3. In my head it's one of those features that's not specific, so the person making the application can decide what they want the active/deactive states to represent. Since you can't log in unless youre active.

**Comment by blomdahldaniel** [comment]
#### 1.
I thought it was something like that
#### 3.
Okey, then I can see why banned might not be appropriate.. But still, active kind of mess around with the whole idea of confirmed and not confirmed accounts.. Could _frozen_ or something like that be a term that would be easier to understand?

#### 2.
Ah, I see! Hm.. In my head, the profile shouldnt be that nested into the dashboard. **The dashboard is the aplications space, not the profile.** I think that should be a separate section. See my examples. I understand what you are going for, you are going for tabs, but in my opinion that is maybe not the best way to go. First, a link to "Edit my profile" or  "Account settings" should always be in  the navbar dropdown-menu. And if we add that, then we would have a link pointing to `/dashboard` but then have to open the tab "My Profile". I dont think thats the way to go actually. They should be separated.

Here's a good example from **Mailgun** that explains my thoughts on a dashboard. The application-bound data, in this case the email-graph should be the main section/purpose. The settings for the user should not be there at all. A simple profile overview of the users data **could** be there but not the entire "My profile". So a summarize, the name maybe profile picture is good but the entire profile and edit edit section should not be there. In this example, Mailgun has a link to **Account settings**
![sceenshot-edited](https://cloud.githubusercontent.com/assets/10044093/19302635/36c7c6a8-9065-11e6-8333-021bd3576371.png)

This is the Dashboard for mailchimp, thats the same case there, but in this case I actually think they did it wrong and complicated when they have a link to Profile and Account. And they are very similar. So not so good imo. But still, this is a dashboard that doesnt even directly refer to the "users space". You access it through the dropdown.
<img width="1567" alt="skarmavbild 2016-10-12 kl 10 29 44" src="https://cloud.githubusercontent.com/assets/10044093/19303389/c5ba3d66-9068-11e6-9ec0-ef7ee2678344.png">

Github is also a great example, they neither have the direct link to settings/edit profile. They keep it in the dropdown.
![skarmavbild-2016-10-12-kl -10 36 39](https://cloud.githubusercontent.com/assets/10044093/19303179/fb19bcd0-9067-11e6-88c0-d07d845785f9.png)

May I create a PR with a refactor of the entire dashboard and edit profile stuff?

**Comment by rappasoft** [comment]
That's a crazy PR i'll have to sift through it.

Unrelated:

I installed yarn on my machine, I think you should all do the same. 

I've just included a **yarn.lock** file with the project, so now when you install, instead of running npm install, you will run **yarn**.

As well as adding packages use **yarn add package_name**, it will update your package.json for you.

This is made by Facebook and is 10x+ faster than npm install.

Also it is included with Laravel installs if you use the **laravel new** command, so I figured it was good to add.

**Comment by rappasoft** [comment]
@blomdahldaniel I don't disagree with your frontend changes.

I think we should get all the backend code refactored and where we like it before we make GUI changes, as to not hold back the launch date of V4.

**Comment by blomdahldaniel** [comment]
Yes, it is a quite crazy PR.. :p But like it states, it is not supposed to be merged in as is but quickly show my idea of the frontend changes.

How should we go about it? Should I wait for some more backend changes or should I create a good solution (frontend and backend) and look for making a PR that should be mergable?

**Comment by minedun6** [comment]
Can we get also to the fact that each time we composer require we need to manually config:cache ?

**Comment by rappasoft** [comment]
What do you mean?

**Comment by rappasoft** [comment]
Merged a few PR's into the upcoming release, what issues do we think are important enough to fix before this is released?

Also I need someone to run the current version and literally go through everything. Try all the functionality, look at the code, let me know if you find anything wrong.

**Comment by num3thod** [comment]
@rappasoft I'll _try_ to give it a go later tonight.

**Comment by blomdahldaniel** [comment]
@rappasoft I'll have a go at it on Wednesday.

**Comment by blomdahldaniel** [comment]
I have now gone through the applications. I've made some small commits:
93707a8 `Fix delete btn event binding for /logs`
122bfaf `add locale all "rights-reserved"` (this might be dirty)
b0e5e4e `when resetting password, prefill email from token`

And a PR that fixes a bug with LogViewer. I made it a PR since it is not probably the best solution but I could not find the error. So you may dig deeper and then see if you can solve it in another way.
#506 

I found a couple of big things that has to be adressed:
# 1. Missing translation for notification email:
I suggest adding most of these into locale --> `strings.php`
### `resources/views/vendor/notifications/email.blade.php` 
Following strings need to be added to locale:
- "Woops!"
- "Hello"
- "Regards"
- "If you’re having trouble clicking the "{{ $actionText }}" button, copy and paste the URL below into your web browser:"

### `app/Notifications/Frontend/Auth/UserNeedsConfirmation.php`
```diff
public function toMail($notifiable){
    return (new MailMessage)
    ->subject(app_name() . ': ' . trans('exceptions.frontend.auth.confirmation.confirm'))
-   ->line(trans('strings.frontend.email.confirm_account'))
-   ->action('Confirm Account', route('frontend.auth.account.confirm', $this->confirmation_code))
-   ->line('Thank you for using our application!');
}
```

### `/vendor/laravel/framework/src/Illuminate/Auth/Notifications/ResetPassword.php`
This one will have to be given locale as well:
```diff
public function toMail($notifiable)
{
    return (new MailMessage)
-        ->line('You are receiving this email because we received a password reset request for your account.')
-        ->action('Reset Password', url('password/reset', $this->token))
-       ->line('If you did not request a password reset, no further action is required.');
}
```
Also fix consistency compared to: `->subject(app_name() . ': ' .  trans('exceptions.frontend.auth.confirmation.confirm'))
`
So add the `app_name()` to subject.

### `resources/views/vendor/notifications/email-plain.blade.php`
Needs same locale changes

# 2. Requested Improvement
- Flash the users email from when the user has clicked "Confirm account" So that the user don't have to fill the email again.
- My suggestion over a new and more inspiring dashboard that is less profile-oriented. And add a new section called _My Profile_ or _Settings_ where the user can change name, email and password. #499 


# Final thoughts
Some work has to be done regarding locale. Don't know if you want to do it yourself to feel comfortable about the variable names and stuff...?

I have tried to look for more things but cannot find anything more as of now. Everything looks great!

**Comment by rappasoft** [comment]
All your PR's look good.

If you have any time to do the stuff in your #1, it would be appreciated.

I'll work on #2.

As for locale, I've never made a real multilingual app so I don't know best practices, I think it works pretty well now, albeit messy, but functional.

**Comment by blomdahldaniel** [comment]
Perf, I will deal with no 1 later this week

**Comment by nasirkhan** [comment]
can we have an option to resend the confirmation email by the user himself? Right now if any user did not receive the email s/he need to ask the admin. only admin can resend the email. It night be helpful is the user her/himself can initiate this resend. what do you think?

**Comment by blomdahldaniel** [comment]
#### 1
No, if the user tries to log in without having confirmed his account, the user will get a flash message that says that the user has to confirm his account OR resend the confirmation email. 
How would you like to implement this in a better way? 

#### 2
Hm… Naah? The whole thing about Gravatar is that you shouln't have to upload or handle the profile picture at all. So all gravatar users should already have accepted this concept and receive that behaviour emediatly...? All websites I have signed up for that uses Gravatar has done it this way. Or do you have an example of a plattform that asks you whether you want to use the gravatar pic or use your own?

**Comment by nasirkhan** [comment]
**2.**
I like Gravatar but not all the users of the application might not have a Gravatar account. So there will be no way to update their profile photo. 
Yes, there is an example platform, https://forum.gitlab.com. register on this forum and try to change the profile photo from the settings. You will see 3 options, system generated, Gravatar, and upload file. I think we can implement this feature here.

**Comment by blomdahldaniel** [comment]
#### 2.
Aah, I think I se your point! I think that Gravatar should be the first option that gets selected by default. But then one can chose wether to use:
- Gravatar
- Personal (upload)
- System default

Is that what you are saying? In that case I am totally on board with your idea.

I think we should do a remake of the _Dashboard/My Profile/Settings_ any way so I think that would be a good feature to add there. One thing though is that we would have to decide is where the app should store the picture. So we should then have to be opinionated about the storage. Not a big thing since defaulting to local storage is ok I guess but we would have to make that decision.

**Comment by nasirkhan** [comment]
@blomdahldaniel updated the previous comment on suggestion **1**.

**Comment by nasirkhan** [comment]
**2**
About the image selection options, we both on the same page now :smile: . Along with the frontend dashboard this profile change option should be available from backend as well. 
We may store the images at `public/img/frontend/user_profile_pic` directory and it will be ignored by default

**Comment by blomdahldaniel** [comment]
😄
Yeah sure `public/img/frontend/user_profile_pic` would be ok.
Backend as well...? All users, no matter roles or permissions, should edit their settings or Profile in the same place in my opinion. Therefore there should only be an option to set the profile pic in the frontend Settings/My Profile area..?

Or do you think there should be a backend option whether the user will be able to edit the profile picture or not? Because in that case I think that would be over-doing it. Just a hardcoded config option would be sufficient in my opinion?

**Comment by rappasoft** [comment]
I believe the current way to store images is in the storage directory, and to create a symlink to public. I remember seeing it somewhere in the laravel docs.

**Comment by num3thod** [comment]
5.3 even has an artisan command to create the link you 
`php artisan storage:link`

**Comment by rappasoft** [comment]
It's up to you guys if you want to build in all these requests before it's released. It's going to push the date back, i'm already behind schedule since I don't have a lot of time to work on it.

It's mostly there minus all the requests.

**Comment by rappasoft** [comment]
Doesn't matter to me if you've contributed or not, I use many projects without doing so. Still want to hear yours and everyone else input if you've used it.

Helps me when I have to use it as well.

**Comment by dafonso** [comment]
IMHO, I'm with @webhanspeter: focus on supporting Laravel 5.3, extra features later. I've found myself other things I'd like to contribute and change, but lacking the time to do it at the moment and also thinking that those maybe aren't really priorities for this project right now. L5.3 is what's **really** needed for all those out there that want to make the leap in new projects, not user pics.

**Comment by num3thod** [comment]
Ok I know this thread is already super long, but what would be the appetite for adding a Toatr middleware? If enabled, it allows you to use toasts for all flash messages, instead of the default bootstrap alerts. Very simple and elegant.

Just a thought, albeit self-serving since it's one of the first things I do when starting a new project with L5B.

**Comment by rappasoft** [comment]
Toastr is already included, but only globally available in the backend js, you can add it to the frontend too if you want in your own project.

**Comment by blomdahldaniel** [comment]
All the missing translations for some of the notification emails should now be fixed (nr **1.** above). I added the new indexes in all the langs but left the english text where there was no translation from before.

**Comment by rappasoft** [comment]
Awesome, we hit the 1000 commit mark with those!

**Comment by nasirkhan** [comment]
Can we set a release date for this version?

**Comment by rappasoft** [comment]
Was trying, but also trying to accomplish all the PRs and Issues in it, and they keep coming in.

**Comment by rappasoft** [comment]
Question, does anyone see a problem or security risk with this? https://github.com/rappasoft/laravel-5-boilerplate/commit/e9810793c85634d146bc49e2da9259bc7ba3e7ae#diff-3040de329d5327de8376a023f4aefc71R22

It adds a user object to every view if the user is logged in so you don't have to pass it through, since its a common object to have.

So instead of doing access()->user() in your views you have access to $user, if the user is logged in.

It's null otherwise.

I just want to make sure i'm not overlooking some security flaw.

**Comment by rappasoft** [comment]
Added a view user view, not only because it's good to have, but to also demonstrate history by entity.

**Comment by nasirkhan** [comment]
If a release date can be decided, then it might be helpful for others who are planning to use this new version. 

A suggestion/query; 
We are using AdminLTE for backend and we did not changed anything within the theme. I think we may change it a little and pull the SASS files form `AdminLTE - node_module`. Otherwise i have to manually update the files in the asset directory.

**Comment by minedun6** [comment]
do you think I can use the development branch for my project or i need to wait ?

**Comment by blomdahldaniel** [comment]
@nasirkhan _You can't have your cake and eat it too_ ;) 
You are perfectly fine to just ditch the entire `sass/backend` folder and use the node_module for AdminLTE instead. However then you have to let go of SASS since AdminLTE only supports LESS in their node package. This project chose SASS and therefore we need all of the files inside the project.

Its hard to set a date on something that is managed in free time. And especially since there is a lot of people sharing ideas and needing help.

**Comment by minedun6** [comment]
Man this will take forever !!!

Le mar. 25 oct. 2016 15:13, Anthony Rappa <notifications@github.com> a
écrit :

**Comment by minedun6** [comment]
If they can hijack laravel auth system then yeah

Le mar. 25 oct. 2016 16:20, Anthony Rappa <notifications@github.com> a
écrit :

**Comment by rappasoft** [comment]
I have accomplished all I want to. There are no PR's left, and minimum issues.

I'm going to go through the entire codebase and release sometime tomorrow.

I wanted to release this version with tests but it will have to be added at a later date at this point.

Look at the development commits to see whats new today and yesterday.

I'll have to update the wiki after it's launched, as well as the installer project won't work until I update that as well.

**Comment by rappasoft** [comment]
RELEASED!
