### ISSUE TITLE
Question: Starter app

### ISSUE THREAD

**Issue by digitalit** [rappasoft/laravel-5-boilerplate#497]
Im so exited to get going with 5.3.

As a BP/Starter kit i really think there should be an example app for let say blogs.

To convert the user app to an blog app for a newbie like me is quite complicated since the user app has so many relationships with permissions and roles i get confused.

It would be so great to have an clean example like blogs for both backend and frontend that one could use as template for creating own functions.

Please consider :)

**Comment by blomdahldaniel** [comment]
That would mean that an entire system for WYSIWYG should be implemented as well? That would require loads of work and code. Code that might not be necessary for others..? In that case this boilerplate would start to look like a CMS. And I guess there is no fault in that but that would mean that the boilerplate would evolve into something much bigger.

After blog managing comes page managing and so on.. The project would enter a completely different state with bigger requirements. I don't say its bad, it would just have to change the whole project and parts of its purpose I think.

**Comment by digitalit** [comment]
I was afraid of this answer but i totally understand :)

**Comment by blomdahldaniel** [comment]
I am not saying this is something that we cannot do. @rappasoft is the one to make those calls of course. But as of how this project has been working so far, this would not be the next step. And I think that this project fills the need of a backend/auth boilerplate. There are other Laravel/Laravel-like CMS'es like [OctoberCMS](https://octobercms.com/) or [Statamic](https://statamic.com/)

**Comment by digitalit** [comment]
i understand, it's just that all other projects I've been looking att sucks compared to this BP so im going to build my own CMS functions based on this BP.

Really not an issue as i use only strict Query Builder. The only thing that is Eloquent is the BP stuff like Users and roles.

So an upgrade for me would be an fresh install of BP 3.5 and then move my stuff and at the same time do adjustments like routes and so on.

My stuff doesn't use model at all, controllers does all logic, repos does all sql.

Trying to find an really strong reason for do the upgrade but i haven't found any yet, maybe you can shed some light as of what i will gain by using Laravel 5.3 over 5.2?

Further more an "real CMS" is not interesting cause my customers cant handle it. My solution is an semi CMS with means that i can choose what part of content my customer can edit and very adapted to specific content so it it nearly impossible to mess up the site.

**Comment by rappasoft** [comment]
My future goal is to have this entire thing modular, I tried once and failed.

Basically I mean all functionality will be held in a Modules folder, and each module has their own Http, Controllers, Routes, Views files, and they hook into the master application.

That way all functionality of each module is held in one place and then we can have a separate repo just for modules to add in. So the boilerplate can remain a boilerplate, but can be extended by the community. That's my end goal.

I tried using this plugin for it once: https://github.com/pingpong-labs/modules

But it was cumbersome and I wanted a way to do it myself so I knew exactly what was going on, but for right now I haven't found a comprehensive guide on making a modular application, since I have never done it.

Maybe that will be version 5, but at this point Laravel updates daily and I have to keep up with everything that changes, like I just posted a commit using the new validation Rule class that came out in 5.3.18 yesterday. 

I will they would hold off on changes and do them like once a month so I can keep up and keep this updated, but this takes up a lot of my time and I'm trying to get this to a stable release so I can take a week off and unwind, since i've been going at this every day since the 5.3.0 release.

In due time, this will get where I want it, but right now I think it's a pretty good starting point for any application large or small.

**Comment by digitalit** [comment]
Sounds great @rappasoft i will stick with your fantastic work and im looking forward to the modular approach.

This would fit me like a glove since my projects then can include different modules depending on the customers need.

Thank you :)
