### ISSUE TITLE
Teams or Groups?

### ISSUE THREAD

**Issue by dambridge** [rappasoft/laravel-5-boilerplate#510]
Curious -- are there any plans to incorporate teams or groups (perhaps something like [Teamwork](https://github.com/mpociot/teamwork) and/or [Landlord](https://github.com/hipsterjazzbo/landlord)? This project looks awesome; I think if teams/multi-tenant was addressed you have a killer.

**Comment by blomdahldaniel** [comment]
Hm.. It seems like great packages both of them.  They also seem quite easy to install. So I think it would make the repo a bit too big/specific to add this for everyone...? I think it is easier if people who wants it just apllies.

**Comment by brentkozjak** [comment]
To me, teams/groups seems generic enough to be included in a boilerplate such as this.  Let’s compare team functionality to say, blogging - blogging is specific functionality and less likely to be required in a generic project.  @blomdahldaniel you're right in saying that integrating the Teamwork package isn’t a great deal of work, however refining the UX (transactional emails, team dashboard etc..) and adding administrative team management into the backend of this boilerplate is significant work - which would lead me to vote for having this included.  Having teams/group management right out of the box make for an awesome SaaS business boilerplate that’s for sure.

**Comment by blomdahldaniel** [comment]
Teams would be generic? Really? A blogg functionality would give you a great amount of WYSIWYG support that could be reused anywhere where some admin or user should be able to manage content. Great feature but that has still shown to be too specific for this boilerplate.

In my head adding teams would make it even more specific. @brentkozjak You talk about the amount of hard work that has to be done? All the UX and all the administrative parts? Well if you would add all of that to this boilerplate, do you still think it would be generic? All the _great deal of work_ would make it **much more** specific. Sure it would be awesome, nice to have. But I definitely think that it is not generic enough to make it fit this boilerplate. But sure, if @rappasoft want to make it an SaaS boilerplate well then this would be suitable. Otherwise, adding teams would clutter up the boilerplate and force more to the user. In my opinion.  

If your looking for a good SaaS then just go get [Spark](https://spark.laravel.com/) its cheep and awesome!

Ofc, @rappasoft is always the one who makes these calls.

**Comment by dambridge** [comment]
@blomdahldaniel I've used both packages and thus far they're pretty solid. Understand your desire to keep this package as 'light' as possible while delivering maximum value. I was interested in how effectively the groups aspect might be incorporated into the overall admin/CRUD backend, as there would be new relationships at play.

With regard to Spark, I've used it a *little* bit so far, and I (and many other folks it seems) find it can be overly opinionated in spots. Your project seems like a perfect alternative, given some kind of tenant/group inclusion.

Hope I didn't stir the pot here though! Will see if I can incorporate any updates myself, although I'm not a professional programmer by any stretch...

**Comment by rappasoft** [comment]
I think Spark is the best bet for obvious reasons.

This project, when I first made it, was to be used for single use applications. Such as a business backend, or something of the sort.

I'm sure it could be used as a bigger application since it has all the pieces, but its really mean to be scaffolding for anything.

I don't want to build in multi-tennancy because then less people will have use for it, I don't see myself doing one anytime soon, but I do build intranets for businesses quite often using it.

I really want to keep it as simple as possible and only include things that will be used in any application regardless of what type.

If you add in this stuff by default it adds bulk and then people will have more problems with other aspects, or it wont work like that want and it will cause a bunch more PR's and issues to deal with.

**Comment by blomdahldaniel** [comment]
@dambridge its always good with input and that people contribute with their thoughts and ideas! So if you would've stirred up the put then that was just great! It makes the project even more secure of its purpose. Or the project could've evolved. 
It's always healthy with discussions! 🙂 Sorry if I came out a bit strong!
