### ISSUE TITLE
request to manage other tables

### ISSUE THREAD

**Issue by donguyenha** [rappasoft/laravel-5-boilerplate#528]
there is only users, roles tables are managed, how to managed other tables - like blogs, categories, posts tables

# What version?
laravel version 5.3.21, laravel-5-boilerplate-4.0.4

**Comment by blomdahldaniel** [comment]
This project is meant to give a good starting point, a boilerplate, for developers that is building applications. This boilerplate gives you management of users and roles. The rest is up to every developer to create by them selves. And since this is a Laravel project you have to learn laravel to understand how to create the rest.

**Comment by minedun6** [comment]
Btw u can use the same patterns that @rappa did while creating this project
u can the code he wrote to do the same.

Le dim. 30 oct. 2016 14:00, Daniel Blomdahl <notifications@github.com> a
écrit :

**Comment by rappasoft** [comment]
Haha you tagged the wrong Rappa XD

**Comment by rappasoft** [comment]
But yes this project gives you all the code you need to create what you want, its just up to you.

**Comment by donguyenha** [comment]
@rappasoft 
could you please give the example for create a controller for managed posts tables, i check there are 1 folder for backend and 1 folder for frontend

which folder should i use for managed posts table

Thank you

**Comment by rappasoft** [comment]
You have all the tools you need. I suggest following the logic of the management of Roles in the backend and you should be fine.
