### ISSUE TITLE
Each access()->can() or  @permission or  @role calls generate new query every time

### ISSUE THREAD

**Issue by safoorsafdar** [rappasoft/laravel-5-boilerplate#557]
Its kinda question, I have no idea why my application started through boilerplate behaving like that but its expected behavior as per the implementation, its executing query every time I call all permission or roles checks related function weather through blade directive or facade helper, and number of queries exceeds over 200 on every request to check permissions and roles.

I think its serious overload burden to application. There is any workaround to minimize the number of queries execution to check permissions or roles.

Sample Queries (Selected through debugger)

```sql
select * from `tbl_user` where `tbl_user`.`deleted_at` is null and `tbl_user`.`credential_id` = '3' and `tbl_user`.`credential_id` is not null limit 1

select `tbl_roles`.*, `tbl_assigned_roles`.`user_id` as `pivot_user_id`, `tbl_assigned_roles`.`role_id` as `pivot_role_id` from `tbl_roles` inner join `tbl_assigned_roles` on `tbl_roles`.`id` = `tbl_assigned_roles`.`role_id` where `tbl_assigned_roles`.`user_id` = '1'

```

#### version
Laravel 5.1 compatible.

Thanks in advance. let me know if question need to expand in further depth.

**Comment by blomdahldaniel** [comment]
Yes, it is a good point to maybe think a bit more on the applications performance regarding the blade extensions. I actually solved it by caching the users roles and permissions for a short period, like 5 min. That improved some of my functionality. I guess it makes the user "invincible" for 5 min where they cannot be banned but I added a clearing of the cache whenever a user (permissions or roles) are changed so that isnt a problem either.

So caching could maybe be a way to go about it?
In that case caching stuff in the model repositories is one way to go. Donno about best practice though.. 

Then to listen for changes and updates you can add [Eloquent Observers](https://laravel.com/docs/5.3/eloquent#observers)

**Comment by blomdahldaniel** [comment]
Yes, it is a good point to maybe think a bit more on the applications performance regarding the blade extensions. I actually solved it by caching the users roles and permissions for a short period, like 5 min. That improved some of my functionality. I guess it makes the user "invincible" for 5 min where they cannot be banned but I added a clearing of the cache whenever a user (permissions or roles) are changed so that isnt a problem either.

So caching could maybe be a way to go about it?

Then to listen for changes and updates you can add [Eloquent Observers](https://laravel.com/docs/5.3/eloquent#observers)

Now I just found this:
https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Repositories/BaseRepository.php#L18

Where the cache is flushed after the actions.. So maybe caching the request would be even easier?

**Comment by safoorsafdar** [comment]
Thank you @blomdahldaniel  yes, thats what i'm thinking about but there is a question, permission and roles only create once you really don't need to provide control user/admin to handle permissions as already implemented in newer boiler versions.  so my question is what about persistent user data like permissions and roles specially permission when user logged in?

**Comment by safoorsafdar** [comment]
Manage to resolve this issue by applying cache techniques using [Handle Duplicate Query](https://laracasts.com/discuss/channels/guides/never-execute-a-duplicate-query-again)

**Comment by blomdahldaniel** [comment]
Interesting, that tutorial technique seems nice. However what does it do with security? And what happens when data is changed? Do you have to flush the cache manually then with Eloquent observers?

**Comment by rappasoft** [comment]
Yeah i'm not sure I want to mess with overriding default functionality at that level (anyone can in their own projects) but if something was over thought I don't want to be the reason a lot of people are having problems. There's probably a different way to do it since there's plenty of access plugins. We will have to look at other code.

**Comment by blomdahldaniel** [comment]
Seems like a reasonable answer! I hope that @safoorsafdar has gotten suggestion how to tackle this. 

Getting to a state with over 200 requests seems a bit odd. Must be able to do that a vit more effective. Maybe set middleware for routes and by that know that the views are safe to show data and therefore no need of blade access checkers. 

I will close this issue for now. If you find a good way to solve this, then please give it here to share with others. :)
