### ISSUE TITLE
html in models/user/traits

### ISSUE THREAD

**Issue by error500** [rappasoft/laravel-5-boilerplate#559]
I recently observe that there is Html code in app/models/users. I had a reflexion about that.. is it the right way ? for example, if i need to design the mail for password reset, is there a way ? Should I migrate in views ?

**Comment by blomdahldaniel** [comment]
Hm.. Im not fully sure I understand what your thinking about. Do you mean the the User model have methods that return html? Such through the trait `UserAttribute` that does some HTML?

In my head, a model may have view specific customisation but only if it is extracted out of the pure model in a nive way. And I think that the trait `UserAttribute` does that perfectly.

Or did I miss your point?

**Comment by error500** [comment]
I just thought that html was reserved to views and helpers. As there is html under the /model makes something strange in the concept : Model is for data persistance and views for presentation
Do you think i'm wrong ?

**Comment by blomdahldaniel** [comment]
I dont think this is a matter where anyone can be wrong or right! :)
Just a matter of taste. 

I understand your point where html belongs to views. And I also see your point with the Model directory controlling objects and data. However I dont have trouble with pulling in a trait that does some magic even though its html. Just because it has a nice abstraction due to the fact its a trait. But, if we would want to be more strict and less cowboy then we should do a refactor and split them up. :)
