### ISSUE TITLE
Laravel slow boot / application

### ISSUE THREAD

**Issue by andrew-za** [rappasoft/laravel-5-boilerplate#578]
This is more a Laravel issue - but wanted to find out from the users of laravel-5-boilerplate if they experience similar issues and what one can try to improve.

**Issue:**
When running laravel from a cold start my debug_bar reports Booting at 8 seconds and Application can also be a few seconds.
Once this initial load subsequent loads are faster at:
Booting (179.94ms)
Application (151.82ms)

**Dev Environment:**
Windows 10 - XAMP (standard settings)

**SQL queries:**
Queries are all fast - without any optimising run at max 100ms total with like 20 queries.

**Comment by blomdahldaniel** [comment]
I have no idea what this can be. There must be something with your setup. Because I guess this is not a problem when the code is put on a real server environment? 

I mainly use valet or homebrew nowadays. And Im on a mass or linux too so dont know much about windows struggles. 

However I have heard that good things about using [laragon](https://laragon.org) on windows.

**Comment by panique** [comment]
Had the same issue, the reason was a too high memory_limit setting in php.ini (make sure you are editing the right php.ini as there are multiple and don't forget to reload nginx/apache). Was 2048M, lowering to 128M increased laravel boot time dramatically!

(I'm commenting here as this issue ranks high in Google for Laravel boot problems)
