### ISSUE TITLE
Undefined property Model::$created_at

### ISSUE THREAD

**Issue by minedun6** [rappasoft/laravel-5-boilerplate#580]
The problem seems kinda odd as I cant created custom accessors.
Here's what I'm trying to accomplish

`
    public function getCreatedAtAttribute()
    {
        return $this->created_at->diffForHumans();
    }`

And it outputs an Undefined property Model::$created_at.

**Comment by blomdahldaniel** [comment]
Hm that seems weird. 

In your migration, do you have the timestamps there? 
```
$table->timestamps()
```

**Comment by minedun6** [comment]
well of course ^^

`
public function up()
    {
        Schema::create('games', function (Blueprint $table) {
            $table->increments('id');
            $table->string('code')->nullable();
            $table->string('name')->nullable();
            $table->timestamp('bought_at')->nullable();
            $table->string('duration')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
    }`

**Comment by blomdahldaniel** [comment]
Sorry, had to ask!

Well, this error is because you try to override the very property that you try to use. But when you try to do that, laravel gives you that property as a value parameter sent into the method (see [docs](https://laravel.com/docs/5.3/eloquent-mutators#accessors-and-mutators)). So you can not access the property that you are  trying to override. If you think about it, It doesnt make sense if you want to write `{{ $user->created_at }}` in your blade and that should give you a diffForHumans. But in your model that same very same line of code should give you the Carbon object.

 So if you want to manipulate an existing property and by that replace the current property through the accessor, then you have to use the incoming `$value`, do it like this:

```php
public function getCreatedAtAttribute($value)
{
    // This works since this is another value, you can access other
    // properties as normal
    return $this->updated_at;

    // this will give you the error you have right now, you cannot access the
    // property you are trying to override.
    return $this->created_at;

    // This is what you want, unfortunately you will loose
    // the laravel date magic when overriding that property.
    // But this will give you the expected result by using $value
    return \Carbon\Carbon::parse($value)->diffForHumans();
}
```

A side-note is that I would not suggest that you override the `created_at` property like this since what you loose is pretty big. You loose the carbon object and then you cannot use it in other places of the project. I would suggest that you create a new accessor and name it to something else. Then you can access the property like expected:

```php
// Calling it: 
$user->createdAtDiff
....
public function getCreatedAtDiffAttribute()
{
    return $this->created_at->diffForHumans()
}
```

Hope this helps!

**Comment by minedun6** [comment]
Much appreciated my friend.

**Comment by blomdahldaniel** [comment]
😀
Glad it helped!
