### ISSUE TITLE
Restore model conflict with new Model

### ISSUE THREAD

**Issue by minedun6** [rappasoft/laravel-5-boilerplate#582]
So the problem is rather obvious, when you use soft deletes on a model, then you add the same model, with the same attributes, it actually outputs that it already exists within your database, if you use the validation "unique" rule.
So what I want to ask is using your solution, how can I maybe merge the two existing rows into one and then get rid of conflict / what can you do if within ur deleted model view, you have the same model, just different id, how can you go about it ?
I hope I'm making myself comprehensible.

**Comment by blomdahldaniel** [comment]
I dont know any easy "laravel magic like" solution for this. You would have to detect the duplication yourself. When detected then override the old data with the new data and set `deleted_at = NULL`. 

I think it would be better if you post this kind of question in the Laravel or laracasts forum since this is not related to the boilerplate in particular.

**Comment by motia** [comment]
You can create a composite unique rule, ```$table->unique(['your_unique_column', 'deleted_at'])```

**Comment by minedun6** [comment]
yeah but it will output a db exception as a result.

**Comment by motia** [comment]
You must drop the old constraint. Try to rollback the migration that defines it, if you can not modify the old migration use ```dropUnique($tablename . '_' . $column_name . '_' . 'unique');``` in another one.
