### ISSUE TITLE
hide phpdebugbar

### ISSUE THREAD

**Issue by pc-mon** [rappasoft/laravel-5-boilerplate#585]
Hello guys 
how can i hide phpdebugbar bar in the bottom 
thank you in advance

**Comment by blomdahldaniel** [comment]
It is disabled when in `.env`:
`APP_DEBUG=false`

**Comment by pc-mon** [comment]
thank you :)

**Comment by pc-mon** [comment]
Still the bar is shown

**Comment by blomdahldaniel** [comment]
That is strange. 
I just tried it out and with a clean install of this repo, the debugbar hides while toggling `APP_DEBUG` in the .env

**Comment by pc-mon** [comment]
I did 
APP_ENV=local
APP_KEY=secret 
APP_DEBUG=false
APP_LOG_LEVEL=debug
APP_URL=http://localhost:8000
APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_LOCALE_PHP=en_US

**Comment by blomdahldaniel** [comment]
Hm.. Again, strange.
However if you put `APP_ENV=production` the ServiceProvider of the debugbar should not even be registered. So that is a fallback that should work 100%. If that does not work, well then you must be editing the wrong file or something. 😛 

You can see it in the [`app/Providers/AppServiceProvider.php:63`](https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Providers/AppServiceProvider.php#L63)

**Comment by pc-mon** [comment]
Worked well :) thank you so much you all
