### ISSUE TITLE
how can i have separate permissions based on user instead of  roles?

### ISSUE THREAD

**Issue by cliffon** [rappasoft/laravel-5-boilerplate#786]
what i want is though 2 two users may have same role ,they could have separate permission ,
I think this could be done using user_permissions relationship,
now what i need help is with ,what part of code i would need to change so that i could use access.routeNeedsPermission after i have changed this relation.

thank you.

**Comment by farrukhsubhani** [comment]
seems to me that you are trying to overcome a self created problem. In real life users have permissions so that we can define a group of users and label them with particular role. In your case it only one user so create a role and assign that user to that role and give permissions to that role. if anyone pick up your code in future they would understand it quickly. I dont see this as an issue its more of a stackoverflow based question.

**Comment by bloggervista** [comment]
I guess for such facility you may require additional tables . But yes as it will be messy i guess.

**Comment by cliffon** [comment]
@farrukhsubhani, @bloggervista , thank you for your inputs , after carefully going through the possible solutions without manipulating much of the core structure , I got my solution.
