### ISSUE TITLE
Is there no permission management gui?

### ISSUE THREAD

**Issue by bloggervista** [rappasoft/laravel-5-boilerplate#791]
hmm i can see we can create roles etc.. here . But I didn't found any section for managing permissions like creating permissions etc.

Is there this feature and is not implemented?
Any reasons or we can create this feature?

Thank you.

**Comment by rappasoft** [comment]
This was a feature and was removed. Manage them I'm your Seeder file. There's no reason to have a UI because you're not going to change them at runtime.

**Comment by bloggervista** [comment]
@rappasoft  Yes I know but how about ability to create permissions while creating roles

Like if you create Manager Role you can create various permissions using repeatable fields.

I guess it will make this be better isn't it?

**Comment by mikimaine** [comment]
@bloggervista You will never do the three CRUD except creating permissions. So If you feel like creating a new permission and attach it to a role, create a database seed for the permission execute that and it will automatically appear on the checkbox in side a role.

**Comment by rappasoft** [comment]
Yeah because you're not creating permissions on the go because they're referenced by name in the code.

**Comment by bloggervista** [comment]
I agree with it :)

**Comment by vesper8** [comment]
this seems weird to me... of course i will add new permissions over time.. just like i will add new roles.. why wouldn't we add new permissions?

as i develop my application I may need to add both new roles and new permissions. Needing to add them to the seeder doesn't make sense to me since you only run the seeder initially.. what if you need to add new permissions after the fact? Yes they are referenced manually in the code, but they still need to be added.. I guess I will add them manually.. or create this CRUD myself.. but I don't understand the logic why they were first added and then removed.. it is a useful thing to have

**Comment by bambamboole** [comment]
@vesper8 its like @rappasoft says. because you reference the permissions and roles by name in the code. thats why you only need new permissions when you push new code. And when you push new code you can create the new roles and permissions. 
I prefer to add the new roles and permissions in a migration, because you can leverage its versioning.

**Comment by bloggervista** [comment]
But still I think there should be permission gui otherwise why would we ever need permission table?

And how you create new roles and permssion in production because doing reseed etc.. is very tedious right?

**Comment by rappasoft** [comment]
You need the permissions table to have id's available to pivot to. You can go the non database way with gates or whatnot but I prefer database driven. You can build a GUI if you want but that's more for us to maintain and doesn't add any real value because it's not needed. We used to have the permission GUI and got rid of it.

**Comment by martinym28** [comment]
It is realy good for project devekoper. But I am confused without the permission GUI general. 

It would be much help If you provide either:
the permission GUI (the best way)
or 
Instructions how to Seed to create a permission with database on
http://laravel-boilerplate.com/5.5/documentation.html
