### ISSUE TITLE
(design question) why ActionButtons in model?

### ISSUE THREAD

**Issue by eduardoarandah** [rappasoft/laravel-5-boilerplate#805]
This is a design question

Are there any advantages of having html and routes inside the model?

http://laravel-boilerplate.com/5.4/documentation.html#action-buttons

I've always used a blade partial if I need to reuse actions for a model, using the `@can` method for authorization
https://laravel.com/docs/5.1/authorization#within-blade-templates

**Comment by Shuyinsama** [comment]
My guess and personal experience would be: Because this is a boilerplate.

I don't think there is any advantage to using the HTML directly inside the Model or it's Repository and Traits but it's a more robust way of adding these to a boilerplate. Allowing for more flexibility in implementation by the user.

If this boilerplate would've used partials it would mean another file to sync and another blade directive to use.

In terms of usability or implementation i'd say there is no actual advantage but more of a preference?
