### ISSUE TITLE
Role Permission Package

### ISSUE THREAD

**Issue by nasirkhan** [rappasoft/laravel-5-boilerplate#814]
I am using the boilarplate for a long time. I really liked the role permission part. do you have any plan to create a separate package out of this?

**Comment by Shuyinsama** [comment]
This was actually discussed in a earlier closed issue: https://github.com/rappasoft/laravel-5-boilerplate/issues/791

tl:dr: Basically the answer is 'no plans'
Mostly because as @rappasoft said, you are not gonna change these at runtime (since that would interfere with current set up roles. Seed your needed roles during setup.

**Comment by bloggervista** [comment]
And from the reply of rappsoft he said he will probably use popular Boucer package. You can check similar package names spatie permission also.

**Comment by rappasoft** [comment]
Switching to the spatie package, I like it a lot and they are well documented and have a history of keeping all of their stuff up to date.
