### ISSUE TITLE
Idea: Bootswatch should be included with Bootstrap 4 during the 5.5 upgrade

### ISSUE THREAD

**Issue by arrakeen** [rappasoft/laravel-5-boilerplate#834]
I found out earlier that you're seriously considering an upgrade to Laravel 5.5.
What do you think about including Bootstrap 4 and the [Bootswatch 4](https://bootswatch.com/4-alpha/) templates during the process?
That should not be a big deal to assume.

**Comment by Shuyinsama** [comment]
The update process has already been started entirely from scratch. A lot of packages need to be replaced with newer supported ones or general better ones. The Frontend is currently being made in Bootstrap 4 and the backend will be a mix of Bootstrap4/CoreUi for CSS and Vue Components. But a couple of packages have no support for BS4 yet so it requires some time. If this process will go as it should then the 5.5 boilerplate will use BS4 but will not include themes for the frontend because a boilerplate should provide the basics. Of course it would be possible to add them yourself as long as the boilerplate uses BS4 at its core.
