### ISSUE TITLE
Modal Not Working Properly

### ISSUE THREAD

**Issue by aneeqtariq143** [rappasoft/laravel-5-boilerplate#980]
when Modal open it displays behind the **"div.modal-backdrop fade show"** even behind the **header**

**Comment by Shuyinsama** [comment]
This has been discussed and looked at numerous time by multiple users. Sadly the main problem lies with Bootstrap instead of the Boilerplate.

We are aware of the issue and continue to look at it to see if we can found a good universal solution but a couple of users have reported different working and for some non-working solutions.
