### ISSUE TITLE
Project requires PHP 7.1 instead of 7.0

### ISSUE THREAD

**Issue by drefined** [rappasoft/laravel-5-boilerplate#988]
Just tried to clone and run composer install. One of the locked dependencies (doctrine/dbal 2.6.3) requires ^7.1 when the project requires >=7.0.0.

**Comment by SketchNI** [comment]
I can't speak for why the project only requires 7.0.x. Since doctrine 2.6.x was released on July 23rd, it has required PHP 7.1. I imagine Doctrine is being used for the built-in database manager so removing it from the dependancies is out of the question and I would strongly recommend not downgrading as that could break things.

The only other option is to upgrade your version of PHP from 7.0.x to 7.1.x.

I dissuade against 7.2 because there is some logic in the application (See #987) that causes some pages to break along no xdebug in the `ondrej/php` ubuntu ppa.

**Comment by rappasoft** [comment]
As of right now that package isn't being used, but was added as a convenience. I don't know if I want to remove the package (probably) or just default to 7.1 (which Laravel isn't yet)
